### ISSUE TITLE
Expose Python interface for other Rust applications?

### ISSUE THREAD

**Issue by kylebarron** [roeap/object-store-python#3]
👋 I'm building [a Rust-Python library](https://github.com/geoarrow/geoarrow-rs/tree/main/python) that depends on object-store. It would be nice to reuse existing Python APIs that are built on object-store, i.e. your crate. From [this comment](https://github.com/PyO3/pyo3/discussions/2340#discussioncomment-2646525) and [this comment](https://github.com/pola-rs/polars/issues/1325#issuecomment-1208607232), I think the primary way to enable this is to split into two crates: an `rlib` crate that contains everything but the actual `#[pymodule]` definition and a `cdylib` crate that is the actual Python module. The former would be able to be depended on by multiple pyo3 libraries, while the latter would be your existing Python package.

I know this is an increase in complexity, but are you interested in a PR for this?

**Comment by roeap** [comment]
Hey @kylebarron - I have been meaning to put some more TLC in this library, as there have been a bunch of updates since last release.

Since the API surface is fairly narrow, I think we can live with a bit more complexity, so yes, quite interested if it makes it more useful :).
